export const FETCH_DEPARTMENT_REQUEST = 'FETCH_DEPARTMENT_REQUEST';
export const FETCH_DEPARTMENT_SUCCESS = 'FETCH_DEPARTMENT_SUCCESS';

export const ADD_DEPARTMENT_REQUEST = 'ADD_DEPARTMENT_REQUEST';
export const ADD_DEPARTMENT_SUCCESS = 'ADD_DEPARTMENT_SUCCESS';
export const ADD_DEPARTMENT_ERROR = 'ADD_DEPARTMENT_ERROR';

export const EDIT_DEPARTMENT_REQUEST = 'EDIT_DEPARTMENT_REQUEST';
export const EDIT_DEPARTMENT_SUCCESS = 'EDIT_DEPARTMENT_SUCCESS';
export const EDIT_DEPARTMENT_ERROR = 'EDIT_DEPARTMENT_ERROR';

export const REMOVE_DEPARTMENT_REQUEST = 'REMOVE_DEPARTMENT_REQUEST';
export const REMOVE_DEPARTMENT_SUCCESS = 'REMOVE_DEPARTMENT_SUCCESS';
export const REMOVE_DEPARTMENT_ERROR = 'REMOVE_DEPARTMENT_ERROR';

export const SELECT_DEPARTMENT = 'SELECT_DEPARTMENT';

// Sockets IO actions

export const SERVER_FETCH_DEPARTMENTS_IO = 'server/fetchDepartments';
export const FETCH_DEPARTMENTS_IO = 'FETCH_DEPARTMENTS_IO';

// export const ADD_DEPARTMENT_REQUEST_IO = 'ADD_DEPARTMENT_REQUEST_IO';
// export const ADD_DEPARTMENT_SUCCESS_IO = 'ADD_DEPARTMENT_SUCCESS_IO';